Various performance improvements
dart-lang/html pull request #251
Opened 2024-07-03 00:33 UTC by moffatman

Should be twice as fast according to my use cases. Happy to discuss what you need for testing, (micro)benchmarking, preserving public API for old slow functions, or whatever else to merge it. I know I still need to do stuff like bump version, changelog, etc.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

2024-08-12 17:24 UTC, kevmoo commented
please run the formatter!

2024-08-13 02:10 UTC, moffatman commented
Idk whether the new `trie.dart` is the right way... maybe something to wait for dart macros

2024-08-13 22:21 UTC, kevmoo requested changes
need to run the formatter, it seems

2024-08-14 00:19 UTC, moffatman commented on lib/src/constants.dart
> +class Charcode {
Thx done

2024-10-29 16:13 UTC, mosuem commented
Closing as the [dart-lang/html](https://github.com/dart-lang/html) repository is merged into the [dart-lang/tools](https://github.com/dart-lang/tools) monorepo. Please re-open this PR there!

2024-10-29 16:13 UTC, closed without merging